#!/usr/bin/env bash
# ============================================================================
# setup-home.sh — recreates the *home-directory* half of the Arch + Hyprland +
# caelestia setup. No sudo, no packages: just the user-owned config files,
# scripts, and git defaults. Run this FIRST, then install.sh for the system half.
#
#     bash ~/Documents/arch-hyprland-setup/setup-home.sh
#
# Generalizable: the desktop monitor connector and its current mode are detected
# at runtime (works whether your ultrawide lands on DP-1, DP-2, HDMI-A-1, ...),
# so this is not pinned to one machine. Idempotent — safe to re-run.
#
# Assumes caelestia is already installed (~/.config/hypr -> caelestia tree).
# ============================================================================
set -uo pipefail

CAE="$HOME/.config/caelestia"
BIN="$HOME/.local/bin"
mkdir -p "$CAE" "$BIN" "$HOME/robotics/ws" \
         "$HOME/.config/fish/conf.d" \
         "$HOME/.config/wireplumber/wireplumber.conf.d" \
         "$HOME/.local/share/dolphin/view_properties/global"

# --- Detect the desktop display + its current mode --------------------------
# Prefer a connected non-eDP output (the external/desktop monitor). Fall back to
# the first monitor, then to DP-1 / a 1080p60 default if Hyprland isn't running.
DESK_CONN="DP-1"; DESK_MODE="1920x1080@60"
if command -v hyprctl >/dev/null && [ -n "${HYPRLAND_INSTANCE_SIGNATURE-}" ]; then
    read -r c w h r < <(hyprctl monitors -j | jq -r \
        '([.[] | select(.name|test("eDP")|not)] + .)[0] | "\(.name) \(.width) \(.height) \(.refreshRate)"')
    [ -n "${c:-}" ] && [ "$c" != null ] && DESK_CONN="$c" && DESK_MODE="${w}x${h}@${r}"
fi
echo ">>> Desktop display detected: $DESK_CONN @ $DESK_MODE"

# ============================================================================
# Hyprland variable overrides
# ============================================================================
cat > "$CAE/hypr-vars.conf" <<'EOF'
# User variable overrides — sourced after caelestia's variables.conf,
# before keybinds.conf, so the $kb* app launchers pick these up.

# Most-used apps on single Super (Super+W / C / E / T)
$browser      = firefox
$editor       = code
$fileExplorer = dolphin

# Cursor — sweet-cursors installed via AUR (see install.sh).
$cursorTheme = sweet-cursors
$cursorSize  = 24
EOF

# ============================================================================
# Hyprland user overrides (sourced LAST — always wins)
# ============================================================================
cat > "$CAE/hypr-user.conf" <<'EOF'
# ============================================================================
# User Hyprland overrides — sourced LAST, so anything here wins.
# Generated by setup-home.sh. Primary display is auto-detected by hdr-toggle.
# ============================================================================

# --- Second / stuck cursor fixes --------------------------------------------
# The "stuck cursor at screen centre" is the DualSense controller's TOUCHPAD
# registering as an absolute pointer — disable it as an input device. (It only
# appears when the controller is plugged in, e.g. for audio.)
device {
    name = sony-interactive-entertainment-dualsense-wireless-controller-touchpad
    enabled = false
}
# Also disable the NVIDIA hardware cursor plane (avoids a separate stale-cursor
# class of bug on RTX cards under Wayland). Harmless if not needed.
cursor {
    no_hardware_cursors = true
}

# --- Per-host monitor config (roaming SSD: desktop / laptop eDP-1) -----------
# hypr-monitors.conf is a symlink flipped by select-monitors.sh at login.
source = $cConf/hypr-monitors.conf
exec-once = ~/.local/bin/select-monitors.sh

# --- App launchers on Super+<letter> ----------------------------------------
# $browser/$editor/$fileExplorer handle Super+W/C/E via hypr-vars.conf.
# Super+G shipped as github-desktop (not installed) → retarget to Chrome.
unbind = Super, G
bind   = Super, G, exec, app2unit -- google-chrome-stable

# Caelestia's idle Super+Alt+E → nemo (not installed); drop it.
unbind = Super+Alt, E

# --- App launchers on Super+Shift+<letter> ----------------------------------
bind = Super+Shift, B, exec, app2unit -- brave
bind = Super+Shift, E, exec, app2unit -- microsoft-edge-stable
bind = Super+Shift, A, exec, app2unit -- antigravity
bind = Super+Shift, D, exec, app2unit -- claude-desktop
bind = Super+Shift, K, exec, app2unit -- kwrite
bind = Super+Shift, I, exec, app2unit -- systemsettings
bind = Super+Shift, N, exec, app2unit -- nvidia-settings
bind = Super+Shift, P, exec, app2unit -- missioncenter
bind = Super+Shift, U, exec, app2unit -- plasma-discover

# --- Caelestia panel toggles -------------------------------------------------
bind = Super+Shift, Y, exec, qs -c caelestia ipc call drawers toggle bar
bind = Super+Shift, O, exec, qs -c caelestia ipc call drawers toggle dashboard
bind = Super+Shift, J, exec, qs -c caelestia ipc call drawers toggle utilities

# --- Minimize / restore (scratchpad-as-minimize) ----------------------------
bind = Super, H,       movetoworkspacesilent, special:minimized
bind = Super+Shift, H, togglespecialworkspace, minimized

# NOTE: half-screen snaps (Super+Ctrl+arrows) are intentionally omitted — that
# chord is caelestia's workspace prev/next, and a float-based snap is unreliable
# on the dwindle layout. Reach for tiling resize (Super+Alt+arrows) instead.

# --- HDR toggle on the primary (non-eDP) display ----------------------------
bind = Super+Ctrl+Alt, H, exec, ~/.local/bin/hdr-toggle
EOF

# ============================================================================
# Per-host monitor configs + active symlink
# ============================================================================
cat > "$CAE/hypr-monitors-desktop.conf" <<EOF
# Desktop: external ultrawide on $DESK_CONN (auto-detected at setup time).
# 10-bit SDR (sRGB), VRR off (overrides global misc { vrr = 1 }) → locked refresh.
# HDR is opt-in per session via Super+Ctrl+Alt+H (hdr-toggle).
monitor = $DESK_CONN, $DESK_MODE, 0x0, 1, bitdepth, 10, cm, srgb, vrr, 0
monitor = , preferred, auto, 1
EOF

cat > "$CAE/hypr-monitors-laptop.conf" <<'EOF'
# Laptop: internal panel on eDP-1. 8-bit (panel max), VRR inherits global misc{vrr=1}.
monitor = eDP-1, 2560x1600@240, 0x0, 1.25
monitor = , preferred, auto, 1
EOF

# Point the active symlink at the right file for the machine we're on now.
if [ -e /sys/class/drm/card*-eDP-1/status ] 2>/dev/null && \
   grep -qx connected /sys/class/drm/card*-eDP-1/status 2>/dev/null; then
    ln -sfn hypr-monitors-laptop.conf "$CAE/hypr-monitors.conf"
else
    ln -sfn hypr-monitors-desktop.conf "$CAE/hypr-monitors.conf"
fi

# ============================================================================
# Scripts in ~/.local/bin
# ============================================================================
cat > "$BIN/select-monitors.sh" <<'EOF'
#!/usr/bin/env bash
# Flip ~/.config/caelestia/hypr-monitors.conf to the right per-host file.
# Laptop = a connected eDP-1 panel exists; otherwise desktop.
set -eu
dir="$HOME/.config/caelestia"
link="$dir/hypr-monitors.conf"
target=hypr-monitors-desktop.conf
for f in /sys/class/drm/card*-eDP-1/status; do
    [ -r "$f" ] || continue
    if [ "$(cat "$f")" = "connected" ]; then
        target=hypr-monitors-laptop.conf
        break
    fi
done
current=$(readlink "$link" 2>/dev/null || true)
if [ "$current" != "$target" ]; then
    ln -sfn "$target" "$link"
    [ -n "${HYPRLAND_INSTANCE_SIGNATURE-}" ] && hyprctl reload >/dev/null
fi
EOF

cat > "$BIN/hdr-toggle" <<'EOF'
#!/usr/bin/env bash
# Toggle HDR <-> sRGB on the primary (non-eDP) display, live (no reload).
# Bound to Super+Ctrl+Alt+H. Detects the monitor and its current mode, so it
# works on any connector/resolution.
set -euo pipefail
MON=$(hyprctl monitors -j | jq -r '([.[] | select(.name|test("eDP")|not)] + .)[0].name')
read -r W H R X Y S STATE < <(hyprctl monitors -j | jq -r --arg m "$MON" \
    '.[] | select(.name==$m) | "\(.width) \(.height) \(.refreshRate) \(.x) \(.y) \(.scale) \(.colorManagementPreset)"')
MODE="${W}x${H}@${R}"
case "$STATE" in
  srgb|unknown)
    hyprctl keyword monitor "$MON, $MODE, ${X}x${Y}, $S, bitdepth, 10, cm, hdr, sdrbrightness, 1.5, sdrsaturation, 1.0"
    notify-send -i video-display "HDR enabled" "$MON • HDR10 / BT.2020"
    ;;
  *)
    hyprctl keyword monitor "$MON, $MODE, ${X}x${Y}, $S, bitdepth, 10, cm, srgb, vrr, 0"
    notify-send -i video-display "HDR disabled" "$MON • sRGB / 10-bit"
    ;;
esac
EOF

cat > "$BIN/ros2-jazzy" <<'EOF'
#!/usr/bin/env bash
# Thin wrapper around the osrf/ros:jazzy-desktop-full Docker image.
# Host ~/robotics/ws is mounted at /root/ws. GPU + X11/Wayland sockets forwarded.
set -euo pipefail

IMAGE="osrf/ros:jazzy-desktop-full"
NAME="ros2-jazzy"
WS="$HOME/robotics/ws"
mkdir -p "$WS"

run_args=(
  --gpus all
  -e DISPLAY="${DISPLAY:-}"
  -e WAYLAND_DISPLAY="${WAYLAND_DISPLAY:-}"
  -e XDG_RUNTIME_DIR=/tmp
  -e QT_X11_NO_MITSHM=1
  -v /tmp/.X11-unix:/tmp/.X11-unix
  -v "${XDG_RUNTIME_DIR:-/run/user/$(id -u)}/${WAYLAND_DISPLAY:-wayland-1}":"/tmp/${WAYLAND_DISPLAY:-wayland-1}"
  -v "$WS":/root/ws
  --network host
)

cmd="${1:-shell}"
case "$cmd" in
  shell)
    if docker ps --format '{{.Names}}' | grep -qx "$NAME"; then
      exec docker exec -it "$NAME" bash
    fi
    exec docker run -it --rm --name "$NAME" "${run_args[@]}" "$IMAGE" bash
    ;;
  run)   shift; exec docker run -it --rm --name "$NAME" "${run_args[@]}" "$IMAGE" bash -lc "$*" ;;
  attach) exec docker exec -it "$NAME" bash ;;
  stop)  exec docker stop "$NAME" ;;
  pull)  exec docker pull "$IMAGE" ;;
  *) echo "usage: ros2-jazzy [shell|run \"<cmd>\"|attach|stop|pull]" >&2; exit 1 ;;
esac
EOF

cat > "$BIN/dualsense-audio" <<'EOF'
#!/usr/bin/env bash
# Route a DualSense controller's audio to the 3.5mm headphone jack and make it
# the default output. The DualSense exposes Speaker vs Headphones as separate
# PipeWire/UCM *profiles*; the jack only produces sound on a Headphones profile.
# Run this when earphones in the controller jack are silent.
set -euo pipefail
CARD=$(pactl list cards short | awk '/Sony|DualSense/{print $2; exit}')
[ -n "${CARD:-}" ] || { echo "No DualSense card found." >&2; exit 1; }
pactl set-card-profile "$CARD" 'HiFi (Headphones, Mic)'
sleep 0.5
SINK=$(pactl list sinks short | awk '/Sony|DualSense/{print $2; exit}')
[ -n "${SINK:-}" ] || { echo "No DualSense sink after profile switch." >&2; exit 1; }
pactl set-default-sink "$SINK"
pactl set-sink-mute   "$SINK" 0
pactl set-sink-volume "$SINK" 70%
command -v notify-send >/dev/null && notify-send -i audio-headphones "DualSense audio" "Routed to 3.5mm headphones"
EOF

chmod +x "$BIN/select-monitors.sh" "$BIN/hdr-toggle" "$BIN/ros2-jazzy" "$BIN/dualsense-audio"

# ============================================================================
# Fish dev-env additions (caelestia owns config.fish — don't touch it)
# ============================================================================
cat > "$HOME/.config/fish/conf.d/dev-env.fish" <<'EOF'
# Personal dev-env additions (caelestia owns config.fish — don't edit that).

# PATH: personal scripts + CUDA
fish_add_path -g $HOME/.local/bin
if test -d /opt/cuda/bin
    fish_add_path -g /opt/cuda/bin
    set -gx CUDA_HOME /opt/cuda
end

# Editors
abbr -ag zed zeditor   # Zed's binary is `zeditor` on Arch

# Tooling shortcuts
abbr -ag lg lazygit

# zoxide (smarter cd) — only if installed
if type -q zoxide
    zoxide init fish | source
end
EOF

# ============================================================================
# Dolphin: hidden files shown by default
# ============================================================================
cat > "$HOME/.config/dolphinrc" <<'EOF'
[General]
GlobalViewProps=true

[KFileDialog Settings]
Places Icons Auto-resize=false
Places Icons Static Size=22
EOF

cat > "$HOME/.local/share/dolphin/view_properties/global/.directory" <<'EOF'
[Dolphin]
HiddenFilesShown=true
Version=4

[Settings]
HiddenFilesShown=true
EOF

# ============================================================================
# WirePlumber: let the DualSense auto-switch to the headphone jack
# ============================================================================
# The controller ships with ACP auto-profile/auto-port OFF, so plugging
# earphones into its jack never moves audio off the internal speaker. Turn them
# on so WirePlumber follows the jack. (Manual fallback: `dualsense-audio`.)
cat > "$HOME/.config/wireplumber/wireplumber.conf.d/51-dualsense-headphones.conf" <<'EOF'
monitor.alsa.rules = [
  {
    matches = [
      { device.name = "~alsa_card.usb-Sony.*DualSense.*" }
    ]
    actions = {
      update-props = {
        api.acp.auto-profile = true
        api.acp.auto-port    = true
      }
    }
  }
]
EOF

# ============================================================================
# Git defaults (identity is left to you — see reminder below)
# ============================================================================
git config --global init.defaultBranch main
git config --global push.autoSetupRemote true
git config --global pull.rebase false
git config --global fetch.prune true
git config --global rerere.enabled true
git config --global core.editor nvim

# ============================================================================
# Apply live if we're inside a Hyprland session
# ============================================================================
if command -v hyprctl >/dev/null && [ -n "${HYPRLAND_INSTANCE_SIGNATURE-}" ]; then
    "$BIN/select-monitors.sh" || true
    hyprctl reload >/dev/null 2>&1 || true
    echo ">>> Hyprland reloaded."
fi

cat <<EOF

Home setup complete. Files written under ~/.config/caelestia, ~/.local/bin,
~/.config/fish/conf.d, and Dolphin config.

Set your git identity (not done automatically):
    git config --global user.name  "Your Name"
    git config --global user.email "you@example.com"

Next: run the system half ->  bash $(dirname "$0")/install.sh
  (it installs git, the GitHub CLI, and an AUR helper up front, so afterward the
   only auth step left is:  gh auth login  &&  git push)
EOF
