#!/usr/bin/env bash
# ============================================================================
# setup-home.sh — recreates the *home-directory* half of the Arch + Hyprland +
# caelestia setup. No sudo, no packages: just user-owned config files, scripts,
# and git defaults. Interactive + component-based, the mirror of install.sh.
# Run this FIRST, then install.sh for the system half.
#
#     bash ~/Documents/arch-hyprland-setup/setup-home.sh            # menu
#     bash ~/Documents/arch-hyprland-setup/setup-home.sh hyprland scripts
#     bash ~/Documents/arch-hyprland-setup/setup-home.sh --yes all
#     bash ~/Documents/arch-hyprland-setup/setup-home.sh --dry-run all  # preview
#
# Flags:
#   --dry-run   show which files each component WOULD write; touch nothing.
#   --yes / -y  skip the confirmation prompt.
#   all         select every component.
#
# Generalizable: the desktop monitor connector + its current mode are detected at
# runtime (works whether your ultrawide lands on DP-1, DP-2, HDMI-A-1, ...), so
# this isn't pinned to one machine. Idempotent — safe to re-run.
#
# Assumes caelestia is already installed (~/.config/hypr -> caelestia tree).
# ============================================================================
set -uo pipefail

CAE="$HOME/.config/caelestia"
BIN="$HOME/.local/bin"
DRY_RUN=0
ASSUME_YES=0

say() { echo -e "$*"; }
hr()  { echo "------------------------------------------------------------"; }
# In dry-run, announce a component's outputs and bail out of the body.
dry() { [ "$DRY_RUN" -eq 1 ] && { say "    [dry-run] would write: $*"; return 0; }; return 1; }

# Set key=value under [Settings] in a GTK settings.ini (create/append as needed).
set_ini_key() {
    local f="$1" k="$2" v="$3"
    mkdir -p "$(dirname "$f")"
    grep -q '^\[Settings\]' "$f" 2>/dev/null || printf '[Settings]\n' >> "$f"
    if grep -qE "^$k=" "$f" 2>/dev/null; then
        sed -i -E "s|^$k=.*|$k=$v|" "$f"
    else
        sed -i "/^\[Settings\]/a $k=$v" "$f"
    fi
}

# ============================================================================
# Components — a row here + a matching do_<name>() teaches setup-home a new one.
# ============================================================================
COMPONENTS=(
    "hyprland|Hyprland overrides (hypr-vars, hypr-user) + per-host monitor configs & active symlink"
    "caelestia|Caelestia shell.json tweaks (weather/dashboard temperature in °C, not °F)"
    "nautilus|Sweet icons: synthwave Sweet-Purple folders + candy app icons as the GTK icon theme (ICON_THEME=<variant> to pick another)"
    # (the daily file manager is nautilus; the old 'dolphin' tweak component was removed)
    "scripts|~/.local/bin helpers: select-monitors.sh, hdr-toggle, dualsense-audio, ros2-humble, vnc-server, remote"
    "fish|Fish dev-env additions (~/.config/fish/conf.d/dev-env.fish)"
    "wireplumber|WirePlumber drop-in so the DualSense auto-switches to its headphone jack"
    "git|Global git defaults (branch, autoSetupRemote, rerere, editor, ...)"
)

do_hyprland() {
    if [ ! -e "$HOME/.config/hypr/hyprland.conf" ]; then
        say "!!! caelestia not detected (~/.config/hypr/hyprland.conf missing)."
        say "!!! Install caelestia first; these files plug into its config tree."
    fi
    # Detect the desktop display + its current mode. Prefer a connected non-eDP
    # output; fall back to DP-1 / 1080p60 if Hyprland isn't running.
    local DESK_CONN="DP-1" DESK_MODE="1920x1080@60" c w h r
    if command -v hyprctl >/dev/null && [ -n "${HYPRLAND_INSTANCE_SIGNATURE-}" ]; then
        read -r c w h r < <(hyprctl monitors -j | jq -r \
            '([.[] | select(.name|test("eDP")|not)] + .)[0] | "\(.name) \(.width) \(.height) \(.refreshRate)"')
        [ -n "${c:-}" ] && [ "$c" != null ] && DESK_CONN="$c" && DESK_MODE="${w}x${h}@${r}"
    fi
    say ">>> Desktop display detected: $DESK_CONN @ $DESK_MODE"
    dry "$CAE/{hypr-vars,hypr-user,hypr-monitors-desktop,hypr-monitors-laptop}.conf + hypr-monitors.conf symlink" && return
    mkdir -p "$CAE"

    cat > "$CAE/hypr-vars.conf" <<'EOF'
# User variable overrides — sourced after caelestia's variables.conf,
# before keybinds.conf, so the $kb* app launchers pick these up.

# Most-used apps on single Super (Super+W / C / E / T)
$browser      = firefox
$editor       = code
$fileExplorer = nautilus

# Cursor — sweet-cursors installed via AUR (see install.sh).
$cursorTheme = sweet-cursors
$cursorSize  = 24
EOF

    cat > "$CAE/hypr-user.conf" <<'EOF'
# ============================================================================
# User Hyprland overrides — sourced LAST, so anything here wins.
# Generated by setup-home.sh. Primary display is auto-detected by hdr-toggle.
# ============================================================================

# --- Stuck / duplicate cursor fixes -----------------------------------------
# The cursor frozen at screen centre is an NVIDIA software-cursor artifact. The
# fix is a CPU cursor buffer WITH hardware cursors enabled. (Forcing
# no_hardware_cursors=true actually *caused* the stale software cursor, so it is
# explicitly off here.) Harmless on non-NVIDIA.
cursor {
    no_hardware_cursors = false
    use_cpu_buffer = true
}
# Secondary: the DualSense touchpad also registers as an absolute pointer that
# parks a cursor at centre when the controller is plugged in. The authoritative
# fix is the libinput udev rule from install.sh; this disables it in Hyprland
# too (applied when the device attaches — replug/relogin to take effect).
device {
    name = sony-interactive-entertainment-dualsense-wireless-controller-touchpad
    enabled = false
}

# --- Per-host monitor config (roaming SSD: desktop / laptop eDP-1) -----------
# hypr-monitors.conf is a symlink flipped by select-monitors.sh at login.
source = $cConf/hypr-monitors.conf
exec-once = ~/.local/bin/select-monitors.sh

# --- App launchers on Super+<letter> ----------------------------------------
# $browser/$editor/$fileExplorer handle Super+W/C/E via hypr-vars.conf.
# Super+G shipped as github-desktop (not installed) → retarget to Chrome.
unbind = Super, G
bind   = Super, G, exec, app2unit -- google-chrome-stable

# Caelestia's idle Super+Alt+E → nemo (not installed); drop it.
unbind = Super+Alt, E

# --- App launchers on Super+Shift+<letter> ----------------------------------
bind = Super+Shift, B, exec, app2unit -- brave
bind = Super+Shift, E, exec, app2unit -- microsoft-edge-stable
bind = Super+Shift, A, exec, app2unit -- antigravity
bind = Super+Shift, D, exec, app2unit -- claude-desktop
bind = Super+Shift, K, exec, app2unit -- kwrite
bind = Super+Shift, I, exec, app2unit -- systemsettings
bind = Super+Shift, N, exec, app2unit -- nvidia-settings
bind = Super+Shift, P, exec, app2unit -- missioncenter
bind = Super+Shift, U, exec, app2unit -- plasma-discover
bind = Super+Shift, Z, exec, app2unit -- zen-browser
bind = Super+Shift, V, exec, app2unit -- obsidian

# --- Caelestia panel toggles -------------------------------------------------
bind = Super+Shift, Y, exec, qs -c caelestia ipc call drawers toggle bar
bind = Super+Shift, O, exec, qs -c caelestia ipc call drawers toggle dashboard
bind = Super+Shift, J, exec, qs -c caelestia ipc call drawers toggle utilities

# --- Minimize / restore (scratchpad-as-minimize) ----------------------------
bind = Super, H,       movetoworkspacesilent, special:minimized
bind = Super+Shift, H, togglespecialworkspace, minimized

# NOTE: half-screen snaps (Super+Ctrl+arrows) are intentionally omitted — that
# chord is caelestia's workspace prev/next, and a float-based snap is unreliable
# on the dwindle layout. Reach for tiling resize (Super+Alt+arrows) instead.

# --- HDR toggle on the primary (non-eDP) display ----------------------------
bind = Super+Ctrl+Alt, H, exec, ~/.local/bin/hdr-toggle
EOF

    cat > "$CAE/hypr-monitors-desktop.conf" <<EOF
# Desktop: external ultrawide on $DESK_CONN (auto-detected at setup time).
# 10-bit SDR (sRGB), VRR off (overrides global misc { vrr = 1 }) → locked refresh.
# HDR is opt-in per session via Super+Ctrl+Alt+H (hdr-toggle).
monitor = $DESK_CONN, $DESK_MODE, 0x0, 1, bitdepth, 10, cm, srgb, vrr, 0
monitor = , preferred, auto, 1
EOF

    cat > "$CAE/hypr-monitors-laptop.conf" <<'EOF'
# Laptop: internal panel on eDP-1. 8-bit (panel max), VRR inherits global misc{vrr=1}.
monitor = eDP-1, 2560x1600@240, 0x0, 1.25
monitor = , preferred, auto, 1
EOF

    # Point the active symlink at the right file for the machine we're on now.
    if [ -e /sys/class/drm/card*-eDP-1/status ] 2>/dev/null && \
       grep -qx connected /sys/class/drm/card*-eDP-1/status 2>/dev/null; then
        ln -sfn hypr-monitors-laptop.conf "$CAE/hypr-monitors.conf"
    else
        ln -sfn hypr-monitors-desktop.conf "$CAE/hypr-monitors.conf"
    fi
}

do_caelestia() {
    # Caelestia reads ~/.config/caelestia/shell.json. The weather/dashboard panel
    # defaults to Fahrenheit (services.useFahrenheit = true); flip it to Celsius.
    # Merge into the existing JSON so other keys (bar, appearance, ...) are kept.
    local f="$CAE/shell.json"
    dry "$f: merge services.useFahrenheit=false (weather in °C)" && return
    mkdir -p "$CAE"
    python3 - "$f" <<'PY'
import json, sys
f = sys.argv[1]
try:
    with open(f) as fh:
        cfg = json.load(fh)
except (FileNotFoundError, json.JSONDecodeError):
    cfg = {}
cfg.setdefault("services", {})["useFahrenheit"] = False
with open(f, "w") as fh:
    json.dump(cfg, fh, indent=4)
    fh.write("\n")
PY
    say ">>> shell.json: weather set to Celsius (services.useFahrenheit=false)."
    # Caelestia watches shell.json and hot-reloads it — no restart needed.
}

do_nautilus() {
    # "Sweet" icons for nautilus & all GTK apps. Two pieces from the 'theme' install
    # component combine into ONE setting:
    #   · candy-icons      — the rainbow/gradient APP icons
    #   · Sweet-<variant>  — coloured FOLDER icons that already Inherit candy-icons
    # So selecting a Sweet-folders variant gives synthwave folders + candy app icons
    # at once. Default Sweet-Purple (synthwave); override with e.g.
    #   ICON_THEME=Sweet-Rainbow bash setup-home.sh nautilus
    # Variants: Sweet-{Purple,Purple-Filled,Rainbow,Red,Blue,Teal,Yellow,Mars}(-Filled).
    #
    # Icons only, no window theme: nautilus is GTK4/libadwaita, whose colours come
    # solely from caelestia's global ~/.config/gtk-4.0/gtk.css palette (gtk-theme /
    # GTK_THEME are ignored), so a per-app window theme isn't feasible.
    # Switch back to the caelestia default with:  bash uninstall.sh icons
    local variant="${ICON_THEME:-Sweet-Purple}"
    dry "icon-theme=$variant (gsettings + gtk-3.0/gtk-4.0 settings.ini)" && return
    if [ ! -d "/usr/share/icons/$variant" ] && [ ! -d "$HOME/.local/share/icons/$variant" ]; then
        say "!!! icon theme '$variant' not installed — run 'bash install.sh theme' (candy-icons + sweet-folders) first."
        return
    fi
    command -v gsettings >/dev/null && \
        gsettings set org.gnome.desktop.interface icon-theme "$variant" 2>/dev/null || true
    set_ini_key "$HOME/.config/gtk-3.0/settings.ini" gtk-icon-theme-name "$variant"
    set_ini_key "$HOME/.config/gtk-4.0/settings.ini" gtk-icon-theme-name "$variant"
    say ">>> GTK icon theme set to $variant (Sweet folders + candy app icons; nautilus & other GTK apps)."
    say "    · relaunch to see them:  nautilus -q   then reopen nautilus."
    say "    · switch back to caelestia default:  bash uninstall.sh icons"
}

do_scripts() {
    dry "$BIN/{select-monitors.sh,hdr-toggle,dualsense-audio}" && return
    mkdir -p "$BIN"

    cat > "$BIN/select-monitors.sh" <<'EOF'
#!/usr/bin/env bash
# Flip ~/.config/caelestia/hypr-monitors.conf to the right per-host file.
# Laptop = a connected eDP-1 panel exists; otherwise desktop.
set -eu
dir="$HOME/.config/caelestia"
link="$dir/hypr-monitors.conf"
target=hypr-monitors-desktop.conf
for f in /sys/class/drm/card*-eDP-1/status; do
    [ -r "$f" ] || continue
    if [ "$(cat "$f")" = "connected" ]; then
        target=hypr-monitors-laptop.conf
        break
    fi
done
current=$(readlink "$link" 2>/dev/null || true)
if [ "$current" != "$target" ]; then
    ln -sfn "$target" "$link"
    [ -n "${HYPRLAND_INSTANCE_SIGNATURE-}" ] && hyprctl reload >/dev/null
fi
EOF

    cat > "$BIN/hdr-toggle" <<'EOF'
#!/usr/bin/env bash
# Toggle HDR <-> sRGB on the primary (non-eDP) display, live (no reload).
# Bound to Super+Ctrl+Alt+H. Detects the monitor and its current mode, so it
# works on any connector/resolution.
set -euo pipefail
MON=$(hyprctl monitors -j | jq -r '([.[] | select(.name|test("eDP")|not)] + .)[0].name')
read -r W H R X Y S STATE < <(hyprctl monitors -j | jq -r --arg m "$MON" \
    '.[] | select(.name==$m) | "\(.width) \(.height) \(.refreshRate) \(.x) \(.y) \(.scale) \(.colorManagementPreset)"')
MODE="${W}x${H}@${R}"
case "$STATE" in
  srgb|unknown)
    hyprctl keyword monitor "$MON, $MODE, ${X}x${Y}, $S, bitdepth, 10, cm, hdr, sdrbrightness, 1.5, sdrsaturation, 1.0"
    notify-send -i video-display "HDR enabled" "$MON • HDR10 / BT.2020"
    ;;
  *)
    hyprctl keyword monitor "$MON, $MODE, ${X}x${Y}, $S, bitdepth, 10, cm, srgb, vrr, 0"
    notify-send -i video-display "HDR disabled" "$MON • sRGB / 10-bit"
    ;;
esac
EOF

    cat > "$BIN/dualsense-audio" <<'EOF'
#!/usr/bin/env bash
# Route a DualSense controller's audio to the 3.5mm headphone jack and make it
# the default output. The DualSense exposes Speaker vs Headphones as separate
# PipeWire/UCM *profiles*; the jack only produces sound on a Headphones profile.
# Run this when earphones in the controller jack are silent.
set -euo pipefail
CARD=$(pactl list cards short | awk '/Sony|DualSense/{print $2; exit}')
[ -n "${CARD:-}" ] || { echo "No DualSense card found." >&2; exit 1; }
pactl set-card-profile "$CARD" 'HiFi (Headphones, Mic)'
sleep 0.5
SINK=$(pactl list sinks short | awk '/Sony|DualSense/{print $2; exit}')
[ -n "${SINK:-}" ] || { echo "No DualSense sink after profile switch." >&2; exit 1; }
pactl set-default-sink "$SINK"
pactl set-sink-mute   "$SINK" 0
pactl set-sink-volume "$SINK" 70%
command -v notify-send >/dev/null && notify-send -i audio-headphones "DualSense audio" "Routed to 3.5mm headphones"
EOF

    # ros2-humble: thin wrapper around the osrf/ros:humble-desktop-full container.
    # Humble (NOT Jazzy) on purpose — it matches Isaac Sim's BUNDLED ROS 2 bridge,
    # which is Humble / Fast DDS 2.6. A Jazzy container crashed Isaac: the two
    # distros encode the ros_discovery_info graph message differently, so Isaac's
    # listener mis-deserialized it and aborted. --network host + a shared
    # ROS_DOMAIN_ID/RMW let it share a DDS domain with Isaac's bridge (Isaac runs
    # natively on driver 580; the NVIDIA Container Toolkit injects that same driver,
    # so --gpus all works).
    cat > "$BIN/ros2-humble" <<'EOF'
#!/usr/bin/env bash
# Thin wrapper around the osrf/ros:humble-desktop-full Docker image.
# WHY Humble, not Jazzy: Isaac Sim's bundled ROS 2 bridge is Humble (Fast DDS 2.6).
# A Jazzy container (Fast DDS 2.14) crashed Isaac because the two distros serialize
# the rmw_dds_common ros_discovery_info (ParticipantEntitiesInfo) graph message
# differently (XCDR v2 vs v1) — Isaac's discovery listener mis-read a length field,
# tried a huge allocation and aborted. Matching the distro removes the mismatch.
#
# Host ~/robotics/ws is mounted at /root/ws. GPU + X11/Wayland sockets forwarded.
# --network host + matching ROS_DOMAIN_ID/RMW let this container share a Fast DDS
# domain with Isaac's bridge.
#
# A Fast DDS XML profile forces UDP-only transport (useBuiltinTransports=false +
# a single UDPv4 transport). Discovery already rides UDP fine across the
# host↔container boundary, but the default shared-MEMORY data transport silently
# drops every sample because native Isaac (UID 1000) and the container (root) can't
# share /dev/shm segments — so `ros2 topic echo`/`hz` saw a publisher but zero data.
# On Jazzy we used FASTDDS_BUILTIN_TRANSPORTS=UDPv4, but that env var doesn't exist
# in Humble's Fast DDS 2.6 (added in 2.10/Iron), so we use the XML profile instead.
set -euo pipefail

IMAGE="osrf/ros:humble-desktop-full"
NAME="ros2-humble"
WS="$HOME/robotics/ws"
PROFILE="$HOME/.config/ros2/fastdds-udp-only.xml"
mkdir -p "$WS" "$(dirname "$PROFILE")"

# Fast DDS 2.6 transport profile: replace the builtin transports (which include
# shared memory) with one UDPv4 transport. Written once — delete it to regenerate.
if [ ! -f "$PROFILE" ]; then
  cat > "$PROFILE" <<'PROFILEEOF'
<?xml version="1.0" encoding="UTF-8" ?>
<dds xmlns="http://www.eprosima.com/XMLSchemas/fastRTPS_Profiles">
  <profiles>
    <transport_descriptors>
      <transport_descriptor>
        <transport_id>udp_only</transport_id>
        <type>UDPv4</type>
      </transport_descriptor>
    </transport_descriptors>
    <participant profile_name="udp_only_participant" is_default_profile="true">
      <rtps>
        <userTransports>
          <transport_id>udp_only</transport_id>
        </userTransports>
        <useBuiltinTransports>false</useBuiltinTransports>
      </rtps>
    </participant>
  </profiles>
</dds>
PROFILEEOF
fi

run_args=(
  --gpus all
  -e DISPLAY="${DISPLAY:-}"
  -e WAYLAND_DISPLAY="${WAYLAND_DISPLAY:-}"
  -e XDG_RUNTIME_DIR=/tmp
  -e QT_X11_NO_MITSHM=1
  -e ROS_DOMAIN_ID="${ROS_DOMAIN_ID:-0}"
  -e RMW_IMPLEMENTATION="${RMW_IMPLEMENTATION:-rmw_fastrtps_cpp}"
  -e FASTRTPS_DEFAULT_PROFILES_FILE=/opt/fastdds-udp-only.xml
  -v "$PROFILE":/opt/fastdds-udp-only.xml:ro
  -v /tmp/.X11-unix:/tmp/.X11-unix
  -v "${XDG_RUNTIME_DIR:-/run/user/$(id -u)}/${WAYLAND_DISPLAY:-wayland-1}":"/tmp/${WAYLAND_DISPLAY:-wayland-1}"
  -v "$WS":/root/ws
  --network host
  --ipc host
)

cmd="${1:-shell}"
case "$cmd" in
  shell)
    if docker ps --format '{{.Names}}' | grep -qx "$NAME"; then
      exec docker exec -it "$NAME" bash
    fi
    exec docker run -it --rm --name "$NAME" "${run_args[@]}" "$IMAGE" bash
    ;;
  run)   shift; exec docker run -it --rm --name "$NAME" "${run_args[@]}" "$IMAGE" bash -lc "$*" ;;
  attach) exec docker exec -it "$NAME" bash ;;
  stop)  exec docker stop "$NAME" ;;
  pull)  exec docker pull "$IMAGE" ;;
  *) echo "usage: ros2-humble [shell|run \"<cmd>\"|attach|stop|pull]" >&2; exit 1 ;;
esac
EOF

    # vnc-server: share THIS Hyprland session over VNC via wayvnc (install.sh 'remote').
    cat > "$BIN/vnc-server" <<'EOF'
#!/usr/bin/env bash
# Share this Hyprland desktop over VNC (wayvnc). Other PCs connect with any VNC
# viewer (Windows: TigerVNC/RealVNC; Linux: remmina/vinagre).
#
#   vnc-server                # bind localhost only (SECURE — reach via SSH tunnel)
#   vnc-server --lan          # expose on the LAN (0.0.0.0) — only on trusted networks
#   vnc-server [--lan] DP-1   # share a specific monitor (default: wayvnc's first)
#
# Secure pattern (default localhost), from the client machine:
#   ssh -L 5900:localhost:5900 <user>@<this-ip>     # then point the viewer at localhost:5900
set -euo pipefail
addr=127.0.0.1
[ "${1:-}" = "--lan" ] && { addr=0.0.0.0; shift; }
out="${1:-}"
command -v wayvnc >/dev/null || { echo "wayvnc not installed — run: bash install.sh remote" >&2; exit 1; }
if [ -n "$out" ]; then exec wayvnc -o "$out" "$addr" 5900; fi
exec wayvnc "$addr" 5900
EOF

    # remote: flip SSH (and stop VNC) on/off per session. sshd is left OFF by
    # default — idle cost is tiny, but off = smaller attack surface.
    cat > "$BIN/remote" <<'EOF'
#!/usr/bin/env bash
# Turn remote access ON only while you need it, OFF when done.
#   remote on       start sshd (accept SSH logins) + show how to reach this box
#   remote off      stop sshd, and stop any running wayvnc (VNC server)
#   remote status   what's listening right now + this box's LAN IP
# sshd is NOT enabled at boot by design. To make it always-on instead:
#   sudo systemctl enable --now sshd
set -euo pipefail
myip() { command ip -4 -o addr show scope global 2>/dev/null | awk '{print $4}' | cut -d/ -f1 | head -1; }
case "${1:-status}" in
  on)
    sudo systemctl start sshd
    echo "sshd  : ON    →  ssh $USER@$(myip)"
    echo "VNC   : run 'vnc-server' when you want screen sharing (on-demand, localhost)"
    ;;
  off)
    sudo systemctl stop sshd
    pkill -x wayvnc 2>/dev/null && echo "wayvnc: stopped" || true
    echo "sshd  : OFF"
    ;;
  status)
    echo "sshd  : $(systemctl is-active sshd 2>/dev/null)"
    if pgrep -x wayvnc >/dev/null 2>&1; then echo "wayvnc: running"; else echo "wayvnc: not running"; fi
    echo "IP    : $(myip)"
    ss -tlnH 2>/dev/null | awk '$4 ~ /:(22|5900)$/ {print "  listening "$4}'
    ;;
  *) echo "usage: remote [on|off|status]" >&2; exit 1 ;;
esac
EOF

    chmod +x "$BIN/select-monitors.sh" "$BIN/hdr-toggle" "$BIN/dualsense-audio" "$BIN/ros2-humble" "$BIN/vnc-server" "$BIN/remote"
}

do_fish() {
    dry "$HOME/.config/fish/conf.d/dev-env.fish" && return
    mkdir -p "$HOME/.config/fish/conf.d"
    cat > "$HOME/.config/fish/conf.d/dev-env.fish" <<'EOF'
# Personal dev-env additions (caelestia owns config.fish — don't edit that).

# PATH: personal scripts + CUDA
fish_add_path -g $HOME/.local/bin
if test -d /opt/cuda/bin
    fish_add_path -g /opt/cuda/bin
    set -gx CUDA_HOME /opt/cuda
end

# Tooling shortcuts
abbr -ag lg lazygit

# zoxide (smarter cd) — only if installed
if type -q zoxide
    zoxide init fish | source
end
EOF
}

do_wireplumber() {
    # The controller ships with ACP auto-profile/auto-port OFF, so plugging
    # earphones into its jack never moves audio off the internal speaker. Turn
    # them on so WirePlumber follows the jack. (Manual fallback: `dualsense-audio`.)
    dry "~/.config/wireplumber/wireplumber.conf.d/51-dualsense-headphones.conf" && return
    mkdir -p "$HOME/.config/wireplumber/wireplumber.conf.d"
    cat > "$HOME/.config/wireplumber/wireplumber.conf.d/51-dualsense-headphones.conf" <<'EOF'
monitor.alsa.rules = [
  {
    matches = [
      { device.name = "~alsa_card.usb-Sony.*DualSense.*" }
    ]
    actions = {
      update-props = {
        api.acp.auto-profile = true
        api.acp.auto-port    = true
      }
    }
  }
]
EOF
}

do_git() {
    dry "global git config (init.defaultBranch, push.autoSetupRemote, ...)" && return
    git config --global init.defaultBranch main
    git config --global push.autoSetupRemote true
    git config --global pull.rebase false
    git config --global fetch.prune true
    git config --global rerere.enabled true
    git config --global core.editor nvim
}

# ============================================================================
# Arg parsing + interactive menu (shared shape with install.sh)
# ============================================================================
SELECTED=()
ALL_NAMES=(); for row in "${COMPONENTS[@]}"; do ALL_NAMES+=("${row%%|*}"); done
is_component() { local n; for n in "${ALL_NAMES[@]}"; do [ "$n" = "$1" ] && return 0; done; return 1; }

for arg in "$@"; do
    case "$arg" in
        --dry-run) DRY_RUN=1 ;;
        -y|--yes)  ASSUME_YES=1 ;;
        all)       SELECTED=("${ALL_NAMES[@]}") ;;
        -h|--help)
            say "usage: setup-home.sh [--dry-run] [--yes] [all | <component>...]"
            say "components: ${ALL_NAMES[*]}"; exit 0 ;;
        *)
            if is_component "$arg"; then SELECTED+=("$arg")
            else say "Unknown component '$arg'. Known: ${ALL_NAMES[*]}"; exit 1; fi ;;
    esac
done

if [ "${#SELECTED[@]}" -eq 0 ]; then
    hr; say "Interactive home setup — pick what to write."
    [ "$DRY_RUN" -eq 1 ] && say "(dry-run: nothing will actually be written)"
    hr
    i=1
    for row in "${COMPONENTS[@]}"; do say "  $i) ${row%%|*} — ${row#*|}"; i=$((i+1)); done
    say "  a) all of the above"
    say "  q) quit"
    hr
    read -rp "Enter numbers (space/comma separated), 'a', or 'q': " reply
    case "$reply" in
        q|Q|"") say "Nothing selected — exiting."; exit 0 ;;
        a|A)    SELECTED=("${ALL_NAMES[@]}") ;;
        *)
            reply=${reply//,/ }
            for tok in $reply; do
                if [[ "$tok" =~ ^[0-9]+$ ]] && [ "$tok" -ge 1 ] && [ "$tok" -le "${#ALL_NAMES[@]}" ]; then
                    SELECTED+=("${ALL_NAMES[$((tok-1))]}")
                else
                    say "  (ignoring invalid choice '$tok')"
                fi
            done ;;
    esac
fi

[ "${#SELECTED[@]}" -eq 0 ] && { say "Nothing selected — exiting."; exit 0; }
in_selected() { local s; for s in "${SELECTED[@]}"; do [ "$s" = "$1" ] && return 0; done; return 1; }

hr
say "Will set up: ${SELECTED[*]}"
[ "$DRY_RUN" -eq 1 ] && say "Mode: DRY-RUN (no changes)."
hr
if [ "$ASSUME_YES" -eq 0 ] && [ "$DRY_RUN" -eq 0 ]; then
    read -rp "Proceed? [y/N]: " ok
    case "$ok" in y|Y|yes|YES) ;; *) say "Aborted."; exit 0 ;; esac
fi

# Run selected components in canonical order.
for row in "${COMPONENTS[@]}"; do
    name="${row%%|*}"
    if in_selected "$name"; then hr; "do_${name}"; fi
done

# Apply live if we wrote Hyprland/scripts config inside a running session.
if [ "$DRY_RUN" -eq 0 ] && { in_selected hyprland || in_selected scripts; } \
   && command -v hyprctl >/dev/null && [ -n "${HYPRLAND_INSTANCE_SIGNATURE-}" ]; then
    [ -x "$BIN/select-monitors.sh" ] && "$BIN/select-monitors.sh" || true
    hyprctl reload >/dev/null 2>&1 || true
    say ">>> Hyprland reloaded."
fi

hr
[ "$DRY_RUN" -eq 1 ] && say "(dry-run: nothing was changed)"
cat <<EOF

Home setup complete.

Set your git identity (not done automatically):
    git config --global user.name  "Your Name"
    git config --global user.email "you@example.com"

Next: run the system half ->  bash $(dirname "$0")/install.sh
  (it installs git, the GitHub CLI, and an AUR helper up front, so afterward the
   only auth step left is:  gh auth login  &&  git push)
EOF
